### ISSUE TITLE
Fatal error on the "Invoice Page setting" page. 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#100]
WP Version - 6.4.2
WC Version - 8.4.0
Plugin Version - V1.3.1_staging
Description - Fatal error on the "Invoice Page setting" page. 

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/0f1c6042-ba7b-4eb9-acdb-1de93d4d30d9)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
