### ISSUE TITLE
Font issue (DejaVu Sans) is not supported  for headers.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#101]
WP Version - 6.4.2
WC Version - 8.4.0
Plugin Version - V1.3.1_staging
Description - The font issue (DejaVu Sans) is not supported for headers. When I selected this Font(DejaVu Sans) for the pdf header, it displayed the deprecated.

Settings - 
1)  PDF Setting > Header > Choose Font Style - DejaVu Sans
2) PDF Setting > Body > Title Font Style - DejaVu Sans
3) PDF Setting > Body > Content Font Style - DejaVu Sans
4) PDF Setting > Footer > Choose Font Style > DejaVu Sans

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/68269897-289d-438c-a2a3-6169824ae53d)

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/7baf2aba-8fb8-43d3-ad08-bfdda23de889)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
