### ISSUE TITLE
PDF Icon Alignment feature is not working. 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#103]
WP Version - 6.4.3
WC Version - 8.5.2
Plugin Version - 1.3.2 
Description - 
When I have selected "Direct Download or Email User/Direct Download or Email Guest"  For Email then the "PDF Icon Alignment
"  feature is not working. 

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/d250a9ae-52bb-42b4-b454-3ed834a40bbe)

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/da2606ab-bd7e-498c-9653-daf2c3aa4828)

**Comment by Puneet-cedcoss** [comment]
![Screenshot from 2024-02-16 12-10-30](https://github.com/wpswings/pdf-generator-for-wp/assets/79438024/269f82e0-77c7-4f02-89b9-5bc3690c599a)
![Screenshot from 2024-02-16 12-10-35](https://github.com/wpswings/pdf-generator-for-wp/assets/79438024/85ba321d-bd82-462b-8ac6-a9db62c4f001)

**Comment by Puneet-cedcoss** [comment]
fix

**Comment by pranjali-wps** [comment]
still pending, when I have enabled direct download then the Right alignment is not working

**Comment by pranjali-wps** [comment]
issue fixed
