### ISSUE TITLE
Email is not getting on Entered Email ID 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#105]
WP Version - 6.4.3
WC Version - 8.5.2
Plugin Version - 1.3.2
Description - If I enter "Email ID" and also check the checkbox of "Use account Email ID instead" then the Email is not getting for Entered email It is only getting on the Wordpress admin email.

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/3ff9f26e-f3d9-48cc-ac4b-39b59c4f4d02)

https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/71ee59cc-246d-4d8d-b4e5-1bd0c2de4c40

**Comment by Puneet-cedcoss** [comment]
Already written on setting -> Use Account  Email Instead

**Comment by pranjali-wps** [comment]
verified
