### ISSUE TITLE
Email template issue 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#106]
WP Version - 6.4.3
WC Version - 8.5.2
Plugin Version - 1.3.2
Description - 1) The email template needs proper punctuation and also Some headings should be bold.
2) The email template should be the same for single and bulk pdf.
![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/fa8d16ea-be55-4a56-9ba1-3dfd675770cd)

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/95415654-cb89-4dfb-b72d-83a2ffccbe21)

**PRO -** 

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/c5ef01b2-2547-46e0-9c0d-ca344f3ef4e7)

**Comment by Puneet-cedcoss** [comment]
fix

**Comment by pranjali-wps** [comment]
issue fixed
