### ISSUE TITLE
Plugin check issue 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#108]
WP Version - 6.4.3
WC Version - 8.7.0
Plugin Version - Plugin check issue 
Description - 

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/a89c254b-14df-4b7c-90dc-7adc36ba6d7d)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
An error is pending 
![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/fa965632-04bd-47b6-899b-b1da7431f1a2)

**Comment by pranjali-wps** [comment]
issue fixed
