### ISSUE TITLE
improper popup is displayed for the PRO plugin.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#109]
WP Version - 6.5.2
WC Version - 8.8.2
Plugin Version -  1.3.4 
Descrption - improper popup is displayed for the PRO plugin.

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/46b78bac-1126-4dbc-a467-54d5b29e3437)

**Comment by Puneet-cedcoss** [comment]
updated

**Comment by pranjali-wps** [comment]
issue fixed
