### ISSUE TITLE
 The media library images are not supported in the pdf. 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#110]
WP Version - 6.5.2
WC Version - 8.8.2
Plugin Version - 1.3.4
Description - The media library images are not supported in the pdf. 

[new post.pdf](https://github.com/wpswings/pdf-generator-for-wp/files/15105087/new.post.pdf)

**Comment by Puneet-cedcoss** [comment]
please check again working everything

**Comment by pranjali-wps** [comment]
verified
