### ISSUE TITLE
There should be added the required Woocommerce.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#112]
WP Version - 6.5.4
WC Version - 8.9.3
Plugin version- 2.4.0
Description - There should be added the required Woocommerce.

![image](https://github.com/wpswings/crm-integration-for-zoho/assets/129398279/8ce47829-af69-475c-b4f1-037891a3ecc9)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
still pending issue 

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/ed656ad1-48ff-4a3b-ace4-2c379ed245f0)

**Comment by prince-cedcoss** [comment]
fix now !!!

**Comment by pranjali-wps** [comment]
fixed
