### ISSUE TITLE
Character encoding issues

### ISSUE THREAD

**Issue by VOOM108** [wpswings/pdf-generator-for-wp#114]
I have been using the plugin for years to allow visitors to download pages and posts as PDF. Recently, the character encoding started to be messed up. It may have started when the site was configured to support two language versions with polylang, but I am not sure. The site is configured to use UTF-8; in German PDFs the Umlaut characters like äöü etc. are not correct:
![image](https://github.com/user-attachments/assets/7cc7b71f-4a82-4c2b-9c29-d1c58a46a0d2)

but in English there are issues as well as with ' characters for example: 
![image](https://github.com/user-attachments/assets/6627a606-a747-4b57-bf1e-e9fd35ed9cf6)

Since the plugin has no encoding settings of its own, what can I do?

**Comment by prince-cedcoss** [comment]
In our September update, we have introduced support for special characters. You can check out this new feature.

**Comment by prince-cedcoss** [comment]
Support for above query is added!
