### ISSUE TITLE
Issue in deactivation.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/pdf-generator-for-wp#47]
**Bug Name -** Issue in deactivation.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.1.1
**WordPress Version -** 5.9
**Plugin Version -** 
**Description -**

![image](https://user-images.githubusercontent.com/76723393/151662515-ff4e9686-500b-42d8-b8a2-b9a03968c9fd.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
will fix in next update

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay

**Comment by Sukirti-CEDCOSS** [comment]
Issue is still there:
![image](https://user-images.githubusercontent.com/85384857/157860550-0e3403ae-50e7-4575-9aa9-4092e63ce817.png)

**Comment by Puneet-cedcoss** [comment]
Org plugin is not deactivated if pro is activated

**Comment by Sukirti-CEDCOSS** [comment]
fine for now
