### ISSUE TITLE
The spacing and place of description are different in different settings

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/pdf-generator-for-wp#51]
WP : 6.0.0
WC: 6.6.0
description:
The spacing and place of description are different in different settings. Place it on the side or below the input field.
![image](https://user-images.githubusercontent.com/85384857/174287260-101b348b-c9e0-4301-aaa6-02e7569cc601.png)
![image](https://user-images.githubusercontent.com/85384857/174287696-bd9b0449-4e83-4f52-b4d2-499b60a44346.png)

**Comment by Puneet-cedcoss** [comment]
the spacing and place of description is automatically adjustable according to the field . this is not an issue

**Comment by Sukirti-CEDCOSS** [comment]
not an issue
