### ISSUE TITLE
Clear the quality of the banner image in the overview 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/pdf-generator-for-wp#54]
WP : 6.0.0
WC: 6.6.0
description: 
Clear the quality of the banner image in the overview 
![image](https://user-images.githubusercontent.com/85384857/174334714-fb3a7a1b-f631-455c-b439-dc2f47c51664.png)
Download as PDF is blurry too
![image](https://user-images.githubusercontent.com/85384857/174714629-a9065730-9c95-4aeb-a628-de06f13e04d7.png)

**Comment by Puneet-cedcoss** [comment]
currently Quality of the banner image is ok ,we will change it in our next update

**Comment by Sukirti-CEDCOSS** [comment]
verified
