### ISSUE TITLE
Change the heading format in the meta field

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/pdf-generator-for-wp#55]
WP : 6.0.0
WC: 6.6.0
description:
Change the heading format in the meta field with the first letter in capital and the rest small of every word.
![image](https://user-images.githubusercontent.com/85384857/174432056-d4e122dc-5a81-4b06-aa1f-cd2f734e423e.png)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
