### ISSUE TITLE
The sale prize is showing wrong amount 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/pdf-generator-for-wp#56]
WP : 6.0.0
WC: 6.6.0
description:
The sale prize is showing wrong amount 
![image](https://user-images.githubusercontent.com/85384857/174433611-1bbeb5ed-18cc-49d2-b688-064d1e7531e6.png)
![image](https://user-images.githubusercontent.com/85384857/174433627-c51c29ee-3cc1-471e-91d9-d2db6adbf18d.png)
![image](https://user-images.githubusercontent.com/85384857/174433639-ac2cafea-1fe4-44a2-8c4b-f4b9614f646f.png)
![image](https://user-images.githubusercontent.com/85384857/174433646-0b0b6802-443e-4601-b708-df283168650b.png)

**Comment by Puneet-cedcoss** [comment]
sale price and price value is same if you want to show regular price then you choose the regular price meta field key , it is not showing the wrong value

**Comment by Puneet-cedcoss** [comment]
In meta fields we have just fetch all meta keys and his saved value we don't change anything only fetch the value from db and show on .

**Comment by Sukirti-CEDCOSS** [comment]
fine for now
