### ISSUE TITLE
Some undefined data is showing in PDF

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/pdf-generator-for-wp#57]
WP : 6.0.0
WC: 6.6.0
description:
Some undefined data is showing in PDF
![image](https://user-images.githubusercontent.com/85384857/174433677-ccbb669d-312d-4861-9988-ada3779f001b.png)
![image](https://user-images.githubusercontent.com/85384857/174433706-bf8079b6-11d1-4812-a012-0b187427f886.png)

**Comment by Puneet-cedcoss** [comment]
working fine

**Comment by Sukirti-CEDCOSS** [comment]
fine for now
