### ISSUE TITLE
The column setting is not working when gallery image meta is added

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/pdf-generator-for-wp#59]
WP : 6.0.0
WC: 6.6.0
description:
The column setting is not working when gallery image meta is added
![image](https://user-images.githubusercontent.com/85384857/174435982-9a512e05-7023-4c3b-8f11-3bcd63a91305.png)
![image](https://user-images.githubusercontent.com/85384857/174435990-72206121-d6f2-45da-b1c3-187c19d4601c.png)
![image](https://user-images.githubusercontent.com/85384857/174436004-a69e49dd-facd-4a70-9da6-d4ccb238fd4e.png)
...............
![image](https://user-images.githubusercontent.com/85384857/174437113-8908cc40-ea9f-4764-9dea-ddba68e00b43.png)
![image](https://user-images.githubusercontent.com/85384857/174437134-7cee0fbb-01e4-4fa9-8abd-f1956dd9751f.png)

**Comment by Puneet-cedcoss** [comment]
![screencapture-localhost-10029-product-non-non-2022-06-20-15_27_43](https://user-images.githubusercontent.com/79438024/174577362-8a9efed9-3388-4d82-86a8-e77522fbeef4.png)
![screencapture-localhost-10029-product-non-non-2022-06-20-15_26_33](https://user-images.githubusercontent.com/79438024/174577371-da9c2164-7f37-4f1d-8671-615f26bd4a09.png)
![screencapture-localhost-10029-product-non-non-2022-06-20-15_18_15](https://user-images.githubusercontent.com/79438024/174577374-e428eac3-46bf-4c5c-8382-ad5c66492765.png)

**Comment by Puneet-cedcoss** [comment]
![screencapture-chrome-extension-fdpohaocaechififmbbbbbknoalclacl-editor-html-2022-06-20-15_27_26](https://user-images.githubusercontent.com/79438024/174577650-2b53aff0-d4cd-4847-9687-f04df6ed2241.png)
![screencapture-chrome-extension-fdpohaocaechififmbbbbbknoalclacl-editor-html-2022-06-20-15_22_18](https://user-images.githubusercontent.com/79438024/174577658-45a96b1d-92db-4c45-bcca-384c1c47bde9.png)

**Comment by Sukirti-CEDCOSS** [comment]
verified
