### ISSUE TITLE
The last edit and attribute metals are not showing the correct values

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/pdf-generator-for-wp#60]
WP : 6.0.0
WC: 6.6.0
description:
The last edit and attribute metals are not showing the correct values
![image](https://user-images.githubusercontent.com/85384857/174436423-e186d6fa-60f0-431d-a8c1-bbef3a62382c.png)

![image](https://user-images.githubusercontent.com/85384857/174436368-1afe6fb1-17e4-4b26-bcc2-b1d41f39163f.png)

**Comment by Puneet-cedcoss** [comment]
values are showing correct but in case of product attribute it is showing Array because it contains the associative array and inside this is another associative array so if this type of meta field is come then simply show Array in place of value

**Comment by Sukirti-CEDCOSS** [comment]
not an issue
