### ISSUE TITLE
Create a homepage under the WP Swings section where all the WP Swings plugins should be listed

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/pdf-generator-for-wp#62]
WP : 6.0.0
WC: 6.6.0
description:
Create a homepage under the WP Swings section where all the WP Swings plugins should be listed
![image](https://user-images.githubusercontent.com/85384857/174724857-ae12cc22-d8b4-4622-9680-40a610c4c13e.png)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
