### ISSUE TITLE
Font option is not working 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/pdf-generator-for-wp#64]
Woo Commerce Version - 6.7.0
WordPress Version - 6.0.1
Plugin Version - 3.0.7
Description - Font is not changing in any segment.
Steps -

1. Go to WP Swings > PDF Generator plugin
2. Select pdf setting option.
3. Go to Header, Body and Footer option.
4. Do some some change in Font.
5. Verify the result.

[PDF-Generator-For-Wp-‹-PDF-Generator-—-WordPress (4).webm](https://user-images.githubusercontent.com/105413021/178753824-1234c079-5916-4073-98de-12e539454d0e.webm)

**Comment by Puneet-cedcoss** [comment]
working check properly

**Comment by ashish-wps** [comment]
Issue fixed.
