### ISSUE TITLE
Plugin Version is not updated

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/pdf-generator-for-wp#65]
Woo Commerce Version - 6.7.0
WordPress Version - 6.0.1
Plugin Version - 1.0.8
Description - Plugin version is not updated and on git version is 1.0.9
Steps -

1. Download the plugin with updated version.
2. Activate the plugin.
3. Verify the result.

![Plugins ‹ PDF Generator — WordPress](https://user-images.githubusercontent.com/105413021/178903726-1263cffc-f669-4a38-9de2-d33e034fd384.png)

**Comment by Puneet-cedcoss** [comment]
updated

**Comment by ashish-wps** [comment]
Fixed
