### ISSUE TITLE
WC and WP is not updated

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/pdf-generator-for-wp#66]
Woo Commerce Version - 6.7.0
WordPress Version - 6.0.1
Plugin Version - 1.0.9
Description - WC and WP is not updated

 * Requires at least:      5.1.0
 * Tested up to:           6.0.1
 * WC requires at least:   5.1.0
 * WC tested up to:        6.7.0

![Screenshot at 2022-07-18 18-45-08](https://user-images.githubusercontent.com/105413021/179519986-f3550c8f-a488-49d7-85eb-1fac28d81fb0.png)

**Comment by Puneet-cedcoss** [comment]
updated

**Comment by ashish-wps** [comment]
Issue Fixed.
