### ISSUE TITLE
phpcs issues

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/pdf-generator-for-wp#68]
Woo Commerce Version - 6.7.0
WordPress Version - 6.0.1
Plugin Version - 1.0.9
Description - phpcs issues

[PHPcs.docx](https://github.com/wpswings/pdf-generator-for-wp/files/9132192/PHPcs.docx)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Issues fixed
