### ISSUE TITLE
pdf plugin is not working on php 8

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/pdf-generator-for-wp#69]
**Woo Commerce Version** - 6.9.2
**WordPress Version** - 6.0.2
**php version** - 8.0.0
**Description** - pdf plugin is not working on php 8
**Steps -**

1. Download and Activate the plugin.
2. Go to the General Settings
3. Enable the plugin.
4. Verify the result.

https://user-images.githubusercontent.com/105413021/190959070-765d1292-cb57-45bf-a365-633616215e76.mp4

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fix
