### ISSUE TITLE
Show error on non-selected User Role

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/pdf-generator-for-wp#70]
**Woo Commerce Version** - 6.9.2
**WordPress Version** - 6.0.2
**php version** - 8.0.0 / 7.4.1
**Description** - Show error on non-selected User Role
**Steps** - 
1. Download and activate the plugin.
2. Go to the WP Swings > PDF Generator for WP 
3. Enable the plugin
4. GO to the pdf setting > icon display 
5. Enable the Show pdf Icon According To User Roles option.
6. Select the user roles.
7. Verify the result.
![pdf generator – Just another WordPress site (1)](https://user-images.githubusercontent.com/105413021/191173247-cf5c55e5-ddbc-409d-a988-e1494359a818.png)

![Beanie – pdf generator](https://user-images.githubusercontent.com/105413021/191173274-de40eb89-cb95-4c7c-bc1d-3a335b79b539.png)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
