### ISSUE TITLE
pdf generator oprtion is not working with pdf upload option on php8

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/pdf-generator-for-wp#71]
**Woo Commerce Version** - 6.9.2
**WordPress Version** - 6.0.2
**php version** - 8.0.0
**Description** - pdf generator oprtion is not working with pdf upload option on php8
**Steps -**
1. Download and activate the plugin.
2. Go to the WP Swings > PDF Generator for WP
3. Enable the plugin
4. Go to the pdf upload and upload poster.
5. Copy the shortcode and on any page and post.
6. Click on pdf generator button.
7. Verify the result.

https://user-images.githubusercontent.com/105413021/191188480-9609257c-d1b4-4e29-81f1-ee4c4e3bb651.mp4

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
