### ISSUE TITLE
Content Font Style issue with Romanian Language 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/pdf-generator-for-wp#72]
**Woo Commerce Version** - 6.9.3
**WordPress Version** - 6.0.2
**php version** - 8.0.0
**Description** - Content Font Style issue with Romanian Language 
**Steps -**

1. Crate a post in Romanian language.
2. Select the DejaVu Sans
3. Create the pdf.
4. Verify the result.

[ashish-wps_72.pdf](https://github.com/wpswings/pdf-generator-for-wp/files/9631150/ashish-wps_72.pdf)

**Comment by Puneet-cedcoss** [comment]
https://www.awesomescreenshot.com/video/11271129?key=47a81c3c15eb73c18ab31dad2bfc0511

**Comment by Puneet-cedcoss** [comment]
[Uploading thiss.pdf…]()

**Comment by Puneet-cedcoss** [comment]
[thiss.pdf](https://github.com/wpswings/pdf-generator-for-wp/files/9632601/thiss.pdf)

**Comment by ashish-wps** [comment]
Fixed
