### ISSUE TITLE
pdf is not generated in flatsome theme

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/pdf-generator-for-wp#73]
Woo Commerce Version - 6.9.3
WordPress Version - 6.0.2
php version - 8.0.0
Description - 
Steps -
1. Download and activate the plugin.
2. Go to the WP Swings > PDF Generator for WP
3. Enable the plugin
4. Enable the Flatsome theme.
5. Generate the theme.

![Screenshot at 2022-09-23 12-55-40](https://user-images.githubusercontent.com/105413021/191911435-31e773a6-6540-4fbb-9f9b-b76610258a3a.png)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
