### ISSUE TITLE
malware issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/pdf-generator-for-wp#74]
**Woo Commerce Version** - 6.9.3
**WordPress Version** - 6.0.2
**php version** - 8.0.0
****Description -** malware issue

https://docs.google.com/document/d/1ShmuUY5xYzxYlZV7T57BZBzP6MUi6avnzpQT4GTcuwg/edit?usp=sharing

**Comment by Puneet-cedcoss** [comment]
this is coming from the libraray

**Comment by ashish-wps** [comment]
Okay
