### ISSUE TITLE
phpcs issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/pdf-generator-for-wp#76]
**Woo Commerce Version** - 7.3.0
**WordPress Version** - 6.1.1
**php version** - 8.0.0
**Description** - phpcs issue

[PHPcs.docx](https://github.com/wpswings/pdf-generator-for-wp/files/10674862/PHPcs.docx)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
