### ISSUE TITLE
no Day in Created Day - Template1

### ISSUE THREAD

**Issue by RickorDD** [wpswings/pdf-generator-for-wp#77]
is there a reason why "Created Date" doesn't show the "day"?

I modified it myself by adding the file 

**pdf-generator-for-wp-admin-template1.php
Line 395**

$created_date = get_the_date( 'F Y', $post );
change to
$created_date = get_the_date( 'j. F Y', $post );

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
