### ISSUE TITLE
Short code copy option didn't work properly 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/pdf-generator-for-wp#78]
**Woo Commerce Version** - 7.4.1
**WordPress Version** - 6.1.1
**php version** - 8.0.0
**Description** - Short code copy option didn't work properly 
**Note** - When user copy one code, both are getting copied.

![image](https://user-images.githubusercontent.com/105413021/224700293-7c7c1c43-7575-45dd-b023-8ad4a6cb73f0.png)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
