### ISSUE TITLE
All Gallery images are not visible in pdf.

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/pdf-generator-for-wp#79]
**Woo Commerce Version** - 7.4.1
**WordPress Version** - 6.1.1
**php version** - 8.0.0
**Description** - All Gallery images are not visible in pdf in Custom Template
**Query** - There are any limitation in gallery images?

![image](https://user-images.githubusercontent.com/105413021/224701811-8da8b1c5-e3dc-412f-a59a-ffc98004c9ed.png)

**Comment by Puneet-cedcoss** [comment]
there is no limitation to show the images . you can use the images in full width . Admin can edit the template and fix

**Comment by ashish-wps** [comment]
Okay
