### ISSUE TITLE
PDF are creating in inappropriate format with Custom Template

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/pdf-generator-for-wp#80]
**Woo Commerce Version** - 7.4.1
**WordPress Version** - 6.1.1
**php version** - 8.0.0
**Description** - PDF are creating in inappropriate format with Custom Template

![image](https://user-images.githubusercontent.com/105413021/224709509-c28ab421-86c3-45b4-bd92-fa057bcc66f9.png)

**Comment by Puneet-cedcoss** [comment]
adjust using the backend settings

**Comment by Puneet-cedcoss** [comment]
And this is custom template admin can design according to their need

**Comment by ashish-wps** [comment]
Okay
