### ISSUE TITLE
Phpcs issues

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/pdf-generator-for-wp#81]
**Woo Commerce Version** - 7.4.1
**WordPress Version** - 6.1.1
**Plugin version** 1.1.4
**Description** - Phpcs issues

[PHPcs.docx](https://github.com/wpswings/pdf-generator-for-wp/files/10963776/PHPcs.docx)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
