### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#82]
WP Version- 6.2.1
WC Version-7.7.0
Plugin version- 1.2.1_staging
![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/3d41a6cd-8d0d-4d89-81e3-42d9f8f26202)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
Issue fixed
