### ISSUE TITLE
Email popup content is not displayed as a popup , it is displayed directly on product page.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#83]
WP Beta version- 6.2.3
WC Beta version - 8.0.0
Description - When I have selected the Email user for **Direct Download or Email User**  setting and also selected **Show PDF Icon** ( except After content and before content position )  on the product page. 

**Show PDF icon fluctuated in this positions**
1. Before add to cart form
2. After add to cart form
3. Before product meta start
4. After single product summary
5. Before single product summary
6. After single product 
7. Before single product
8. After share button 

- ![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/75a3f167-77de-4735-a1c7-519652a67149)

-![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/af9d961d-894f-443a-ae1f-c3926cfdc52a)

**Also pop-up is not properly**
![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/a01f6e1f-4006-44cf-8e16-8922c049a9ee)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
