### ISSUE TITLE
Content issue

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#84]
WP Beta version- 6.2.3
WC Beta version - 8.0.0
Description -  Incorrect content
**1**
![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/e2183bd0-6661-4640-b2a0-0b9971d38e51)

**2** First letter should be capital not last letter
![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/76267dc2-70cc-4977-ab78-2cebbb2d5e1f)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
