### ISSUE TITLE
Pro tag should be added on internal page.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#85]
WP Beta version- 6.2.3
WC Beta version - 8.0.0
Description - Pro tag should be added on the internal page and also add the pro tag entire internal page and pdf logs page
![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/d0023de0-d821-4f90-9fef-3f96342a6fe5)

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/b7a4539b-1a42-4d09-8509-025247d60fc0)

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/60e77d8c-6354-4d4d-8621-e27b7b719048)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by Puneet-cedcoss** [comment]
pro tag is added on entire internal page .

 adding pro tag for seprate cover page and internal page is not looking quite good that's why it's added on pro tag on only main strip which is showing pro tag for both cover page and internal page

**Comment by Sukirti-CEDCOSS** [comment]
verified
