### ISSUE TITLE
Poster icon and pdf icon is conflicted when I have selected the after content 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#86]
WP Beta version- 6.2.3
WC Beta version - 8.0.0
Theme name- Storefront

Description - The poster icon and pdf icon is conflicted when I have selected the **Show PDF Icon**feature (after content).
![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/75038585-796d-4d0f-aafc-f8b51096868e)

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/98202550-7b38-4324-a543-c80fe39aed62)

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/c43bc43f-eb1e-430d-b2c8-70fbceb5e8f4)

**Comment by Puneet-cedcoss** [comment]
![Screenshot from 2023-08-07 10-23-48](https://github.com/wpswings/pdf-generator-for-wp/assets/79438024/8d18a034-d2d7-4212-8e98-c25fb01ace97)
![Screenshot from 2023-08-07 10-24-16](https://github.com/wpswings/pdf-generator-for-wp/assets/79438024/cd99a4ae-6a6f-4c6f-859d-dc1043ec14b6)
![Screenshot from 2023-08-07 10-24-40](https://github.com/wpswings/pdf-generator-for-wp/assets/79438024/01c19311-49b9-4e1d-98bf-b2ee2b6e3f96)

**Comment by Puneet-cedcoss** [comment]
please use it properly

**Comment by Puneet-cedcoss** [comment]
working fine

**Comment by Sukirti-CEDCOSS** [comment]
need to space between icon
