### ISSUE TITLE
Phpcs issue

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#87]
WP Beta version- 6.2.3
WC Beta version - 8.0.0
Description - Phpcs issue
[PHPcs PDF.docx](https://github.com/wpswings/pdf-generator-for-wp/files/12215593/PHPcs.PDF.docx)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
