### ISSUE TITLE
 The "Display post date" feature is not working properly. If I have disabled this featured the Current date also hides.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#89]
WP version- 6.3.1
WC version- 8.1.1
Plugin- 1.2.6_staging
Description- The "Display post date" feature is not working properly. If I have disabled this featured the Current date also hides.
![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/754aea0f-e186-4f9b-b338-79f0941bc357)

**Comment by Puneet-cedcoss** [comment]
new setting created and issue fixed

**Comment by pranjali-wps** [comment]
issue fixed
