### ISSUE TITLE
In "Date format", Please clarify the proper date formats.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#90]
WP version- 6.3.1
WC version- 8.1.1
Plugin- 1.2.6_staging
Description - In "Date format", Please clarify the proper date formats.
![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/f2c94e2a-f513-41c6-84fc-fe656e1789b8)

**Comment by Puneet-cedcoss** [comment]
all the date format's are correct

**Comment by pranjali-wps** [comment]
verified
