### ISSUE TITLE
If I have only chosen "Custom page size" and do not enter any data then a Fatal error is displayed.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#91]
WP version- 6.3.1
WC version- 8.1.1
Plugin- 1.2.6_staging
Description - If I have only chosen "Custom page size" and do not enter any data then a Fatal error is displayed.

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/5f81876c-eb78-4262-bb0f-044fea6933b0)

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/6d4cb70a-f2f2-4034-8c64-e06b6ad29fc4)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
