### ISSUE TITLE
 If I have only chosen "Custom page size" and entered any data then a Fatal error and deprecated is displayed.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#92]
WP version- 6.3.1
WC version- 8.1.1
Plugin- 1.2.6_staging
Description - If I have only chosen "Custom page size" and entered any data then a Fatal error and deprecated is displayed.

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/97b3c7ba-5699-4ca9-b664-0102989f7904)

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/81739908-9ee9-4ee6-b429-ba2b32b84aac)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
