### ISSUE TITLE
 If I have chosen "Select option" in the Page template it displays a fatal error.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#93]
WP version- 6.3.1
WC version- 8.1.1
Plugin- 1.2.6_staging
Description - If I have chosen "Select option" in the Page template it displays a fatal error.
![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/f4026a9e-6c51-477d-9234-1def89a40a54)

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/3d0ad081-ac33-4017-9348-e3c663833690)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
