### ISSUE TITLE
If I have chosen "Select option" in the Body template it displays a fatal error. 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#94]
WP version- 6.3.1
WC version- 8.1.1
Plugin- 1.2.6_staging
Description - If I have chosen "Select option" in the Body template it displays a fatal error.  (Body)
![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/3e27e0dd-9276-45bb-99ef-17ea5b2ddd7e)

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/d39089d9-92c5-4870-b7e5-9cffde88a4fd)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
verified
