### ISSUE TITLE
The poster icon and pdf icon are conflicted with each other. 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#95]
WP version- 6.3.1
WC version- 8.1.1
Plugin- 1.2.6_staging
Description -The poster icon and pdf icon are conflicted with each other. 
Theme- storefront
![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/3a64a826-23cd-4f3a-9ba8-26b9f677fec8)

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/4b1f6b9c-0e36-4430-b5b2-8d78cd0baf33)

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/8c2bfea7-6cb0-447f-843c-39c89b190658)

**Comment by Puneet-cedcoss** [comment]
use proper spacing after content

**Comment by pranjali-wps** [comment]
verified
