### ISSUE TITLE
The Poster icon and pdf icon fluctuate with each other in different themes.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#96]
WP version- 6.3.1
WC version- 8.1.1
Plugin- 1.2.6_staging
Description - The Poster icon and pdf icon fluctuate with each other in different themes.
![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/d8d1c816-68a3-437c-87b2-eab9497a9f5d)

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/9b786a65-ea66-4177-b677-f5aadd6434a7)
![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/077282f7-8009-4524-becc-6afc9892f761)

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/01837744-893d-42c6-a4b3-f6c6d5e71971)

**Comment by Puneet-cedcoss** [comment]
Not an issue use proper spacing after content

**Comment by pranjali-wps** [comment]
verified
