### ISSUE TITLE
Write the description in the proper place.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#97]
WP version- 6.3.1
WC version- 8.1.1
Plugin- 1.2.6_staging
Description - Write the description in the proper place.
![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/ec3a3b81-8535-4974-97ba-0114fbafbe17)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
