### ISSUE TITLE
 The Plugin is unable to activate. It is triggered by a fatal error.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/pdf-generator-for-wp#99]
WP Version - 6.4.2
WC Version - 8.4.0
Plugin Version - V1.3.1_staging
Description - The Plugin is unable to activate. It is triggered by a fatal error.

![image](https://github.com/wpswings/pdf-generator-for-wp/assets/129398279/f7896827-d5df-4974-acf0-b63e0bf7ccb6)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
it is fixed now
